const DEFAULT_RESTAURANTS = [
  {name:"Chicago Pizza",location:"",type:"Pizza, Wings",comments:"",url:""},
  {name:"Chili Thai",location:"Orleans",type:"Thai",comments:"Won awards",url:"https://www.chilithai.ca/"},
  {name:"Lunergan's Pub",location:"",type:"Pub",comments:"",url:"https://www.facebook.com/Lunerganspub/"},
  {name:"Palermo's Pizzeria",location:"",type:"Pizza, Donairs",comments:"",url:"https://palermos.ca/"},
  {name:"Chuck's Roadhouse",location:"1100 Baxter Rd",type:"",comments:"",url:""},
  {name:"Datsun",location:"Elgin Street",type:"Noodles, Dumplings",comments:"",url:""},
  {name:"Marlborough Pub and Eatery",location:"Rogers Stevens Dr, North Gower",type:"Pub",comments:"",url:""},
  {name:"At Loose Wings",location:"Train Yards",type:"Wings",comments:"",url:""},
  {name:"Fat Boys Southern Smokehouse",location:"",type:"BBQ, Smokehouse",comments:"",url:""},
  {name:"Somewhere Dine Bar",location:"",type:"",comments:"Tammy's son is chef",url:""},
  {name:"Cantina Gia",location:"",type:"",comments:"",url:""},
  {name:"Pelican Seafood Market and Grill",location:"",type:"Seafood",comments:"Featured on Diners, Drive-Ins and Dives",url:""},
  {name:"Occo Kitchen and Bar",location:"",type:"Donair",comments:"",url:""},
  {name:"Mermaid's Seafood Restaurant",location:"Walkley",type:"Seafood",comments:"",url:""},
  {name:"Paper Tiger Noodle Bar",location:"",type:"Noodles",comments:"",url:""},
  {name:"Burgers and Fries Forever",location:"329 Bank Street",type:"Burgers, Fries",comments:"Really good birria fries",url:""},
  {name:"Kelly's Landing",location:"",type:"",comments:"",url:""},
  {name:"Black Dog Bistro",location:"",type:"Bistro",comments:"",url:""},
  {name:"Gyubee Japanese Grill",location:"Merivale",type:"Japanese",comments:"",url:""},
  {name:"Centertown Halifax Donair & Pizza",location:"",type:"Donair, Pizza",comments:"Owner: Terry-Lynn",url:"https://centertownhalifaxdonairandpizza.ca/"},
  {name:"Black Dog",location:"Manotick",type:"Bistro",comments:"",url:""},
  {name:"52 Sandwiches",location:"",type:"Sandwiches",comments:"",url:""},
  {name:"Smash Daddy's",location:"",type:"Burgers",comments:"",url:""},
  {name:"Pi Squared Pizzeria",location:"",type:"Pizza",comments:"",url:"https://pisquaredpizzeria.com/"},
  {name:"Bergham",location:"",type:"Wraps",comments:"",url:""},
  {name:"Sunset Grill",location:"",type:"Breakfast",comments:"",url:""},
  {name:"Umbrella Burger",location:"",type:"Smash Burger",comments:"",url:""},
  {name:"Chirpy Chips",location:"Canadian Tire, Merivale",type:"Poutine",comments:"Food truck. Known for poutine",url:""},
  {name:"JJ's Wings",location:"By Clyde Ave",type:"Chicken Wings",comments:"Food truck",url:""},
  {name:"Summerhays",location:"",type:"",comments:"$5.95 for 1lb after 2:30pm",url:"https://www.summerhaysgrill.ca/"},
  {name:"Don Floriano",location:"",type:"Pizza, Sandwiches",comments:"",url:"https://donfloriano.ca/"},
  {name:"Noodle House 79",location:"",type:"Noodles",comments:"",url:"https://noodlehouse79.com/menu"},
  {name:"Mu Goong Hwa Garden",location:"",type:"Korean BBQ",comments:"Best overall Korean BBQ in the city",url:""},
  {name:"Gogiya",location:"Rideau",type:"Korean BBQ",comments:"Best overall Korean BBQ in the city",url:""},
  {name:"Korean House",location:"Chinatown",type:"Korean",comments:"More limited menu. Chef is Vietnamese but trained and worked in Korea",url:""},
  {name:"Yummy Touch Kitchen",location:"",type:"",comments:"",url:""},
  {name:"Saboroso Bistro",location:"",type:"Philippine",comments:"",url:""},
  {name:"O Frango",location:"",type:"",comments:"",url:"https://www.ofrango.ca/"},
  {name:"Pure Kitchen",location:"",type:"Vegetarian, Vegan",comments:"",url:""},
  {name:"Black Pug",location:"Off Kilburn",type:"",comments:"",url:""},
  {name:"Al's Drive In",location:"Osgoode",type:"",comments:"",url:"https://alsdrivein.ca/"},
  {name:"Rock's Deli",location:"",type:"Smoked Meat, Smash Burgers",comments:"",url:"https://rockndeli.com/"},
  {name:"Hidden Taste",location:"Orleans",type:"Indian",comments:"Butter chicken",url:""},
  {name:"Seau de Crane",location:"Orleans",type:"Seafood",comments:"",url:""},
  {name:"Heist",location:"Manotick",type:"",comments:"",url:""},
  {name:"Greek Village Souvlaki",location:"",type:"Greek",comments:"Authentic Greek food",url:""},
  {name:"Al's Steakhouse",location:"",type:"Steak",comments:"",url:"https://www.alssteakhouse.ca/"},
  {name:"Shawarma Al Mouna",location:"",type:"Shawarma",comments:"",url:""},
  {name:"Thai Bite",location:"Orleans",type:"Thai",comments:"Awesome pad thai, pad sou",url:"https://www.thaibite.ca/"},
  {name:"50 Two Sandwiches and More",location:"",type:"Sandwiches",comments:"Candy club sandwich \u2014 get it jalape\u00f1o cheddar",url:""},
  {name:"Bite Burger",location:"",type:"Burgers",comments:"",url:"https://biteburgerhouse.com/"},
  {name:"Yalla Yalla Bakery",location:"Orleans",type:"Bakery",comments:"",url:""},
  {name:"Soul Stone Sushi Grill",location:"Orleans",type:"Sushi",comments:"",url:""},
  {name:"Weis Noodle House",location:"Orleans",type:"Noodles, Thai",comments:"Good pad Thai. Ask for extra sauce",url:"https://weisnoodlehouse.ca/"},
  {name:"Chicken Street",location:"",type:"Chicken",comments:"",url:"https://www.chickenstreet.ca/"},
  {name:"The Great Canadian Poutinerie",location:"",type:"Poutine",comments:"Best general tao poutine",url:""},
  {name:"Crab Boil",location:"",type:"Seafood",comments:"",url:""},
  {name:"Persis Grill",location:"Bells Corners",type:"Persian",comments:"Really good eggplant app. Beef tenderloin and other kebabs",url:""},
  {name:"Mr Laziz",location:"",type:"",comments:"",url:""},
  {name:"D-Luxe Cafe",location:"Hunt Club & Merivale",type:"Indian",comments:"Tandoori chicken",url:""},
  {name:"Pizza and Smash Burger",location:"Off Walkley",type:"Pizza, Smash Burger",comments:"",url:""}
];

const DEFAULT_MOVIES = [
  {title:"The Grand Seduction",genre:"Comedy/Drama"},
  {title:"The Red Violin",genre:"Drama"},
  {title:"1883",genre:"Western/Drama Series"},
  {title:"Cabinets of Mystery",genre:""},
  {title:"One (Jet Li)",genre:"Action"},
  {title:"Ted Lasso",genre:"Comedy Series"},
  {title:"Tulsa King",genre:"Crime/Drama Series (Paramount)"},
  {title:"The Last Manhunt",genre:"Western"},
  {title:"Murder at Yellowstone City",genre:"Western/Thriller"},
  {title:"John Q",genre:"Drama/Thriller (Netflix)"},
  {title:"Yellowstone",genre:"Western/Drama Series"},
  {title:"1923",genre:"Western/Drama Series"},
  {title:"Violent Night",genre:"Action/Comedy"},
  {title:"Glass Onion",genre:"Mystery/Comedy"},
  {title:"The Last of Us",genre:"Drama/Sci-Fi Series"},
  {title:"Ambulance",genre:"Action/Thriller"},
  {title:"Waiting",genre:"Comedy"},
  {title:"Letters from Iwo Jima",genre:"War/Drama"},
  {title:"The Fall Guy",genre:"Action/Comedy"},
  {title:"Free Bert",genre:"Series"},
  {title:"The Pitt",genre:"Drama Series"},
  {title:"Landman",genre:"Drama Series"},
  {title:"Accentia",genre:""},
  {title:"Night of 7 Kingdoms",genre:""},
  {title:"The Mayor of Kingstown",genre:"Crime/Drama Series"},
  {title:"Mr Mercedes",genre:"Crime/Thriller Series"},
  {title:"Marshals",genre:"Western Series (Yellowstone sequel)"},
  {title:"The Madison",genre:"Drama Series (Netflix)"},
  {title:"Stray",genre:""}
];
